---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hf-token
  namespace: default
spec:
  encryptedData:
    HUGGING_FACE_HUB_TOKEN: AgBC7ALyiojOmWGE1edSPAVSqnNAbxcXSY3cv0evfhZdGCFE7pRgFLdEdm6R3T9yAu5ieSv5waOpL2BP9cuTba1PfsCZUBzS9WTv6R/Y5z/oSMxsBRMjYmafJzwnw2yO3iQSJ0AWhbyK0xVi2e3WoVj5H4KHrn3w4ggoRoVBCjE8MgiAsZ3TrQ8+6bce3W3pj5a5B+tJHbLN3tzLZfXm9/UQEVivjq/ZPzftsNpxd+pbZ3QnRD7fEZCLuuxZpj+oKG7ma5k2RzV9PreElrtVsSLagz0pHRNKo0sK6rZeW1zuT4SUjMmE3wgULq9Pyb8DsV7LinLfdKTS7hOsp3c49m4ib5kfgr961+T/YCirrl3ypgU5jZwLXRnhxpXc6pY1EJfRhB+xUe1xgKhaL6toVfjqf8YdQvZJ/wJqjRZ+WoaFZF8D0ZqbhGZ9Gt5qRVGjdwREwAfxb4mrQ+pPKfQzHL5KOv4gqB6CprJfMQJo2g4vft9cMTH8T61pEsai76MOxIc/Eu5UDCDBzqsWhtDppusotRZmNVC7ugzH34J5MsH+fgJIDSFdusGWfEbqrZwZJvTrPl7/StyGj4jTaJ1CPj0D1mfjU2L+WMEcnStXCn7SjV5UdS0VhExC9R+5R+yVot+8UL7dzO7+zWT3/TMpCHIT4JOcYod3OvUsMkuelw6Z+Ydr5Z65JZxtAhOZUlhqz5wDrQxkaRBd6Uaec0tpl93gHlOpZihh0WL8C96G234UvhFiNtP1
  template:
    metadata:
      name: hf-token
      namespace: default
